services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user_management_database'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'